export type Lang = "es" | "en";

export const COPY = {
  es: {
    nav: ["Servicios", "Principios", "Trabajo", "Nosotros"],
    cta_nav: "Hablemos",
    hero_eyebrow: "Ventas digitales con IA · LATAM",
    hero_title: ["Tecnología que", "crece", "con tu negocio"],
    hero_sub:
      "Diseñamos y desarrollamos las plataformas digitales que tu negocio necesita: chatbots con IA en web y redes, sistemas automatizados y tiendas en línea. Tecnología lista para escalar cuando tú lo hagas.",
    hero_cta: "Agendar diagnóstico",
    hero_cta_2: "Ver nuestros servicios",
    clients_eyebrow: "Equipos y marcas con las que construimos",
    clients_title: "Empresas que confían en nosotros para escalar",
    sites_scroll_eyebrow: "Sitios en producción",
    sites_scroll_aria: "Sitios web que creamos",
    sites_scroll_lead: "Creamos sitios web que",
    sites_scroll_switcher: "Cambiar de sitio",
    sites_scroll_open: "Abrir",
    sites_scroll_pending: "Vista no disponible.",
    stats: [
      { k: "24/7", v: "respuesta en tus canales" },
      { k: "1", v: "sistema del lead al cierre" },
      { k: "IA", v: "en web, WhatsApp y redes" },
      { k: "LATAM", v: "operación y soporte" },
    ],
    services_eyebrow: "¿Cómo impulsamos tu negocio?",
    services_title: "Nuestros servicios",
    services_title_accent: "end to end.",
    services_sub:
      "Tienda, chatbot, automatización, CRM e incluso sistemas a medida: cada capa se diseña para que el lead no se enfríe. Cuando los ads ya traen gente, miramos el cierre — y lo volvemos medible.",
    services: [
      {
        tag: "01",
        name: "E-commerce",
        desc: "Tiendas y catálogos pensados para convertir: checkout, pagos locales, inventario y conexión con tu conversación comercial.",
      },
      {
        tag: "02",
        name: "Chatbots con IA",
        desc: "Atención y calificación en web, WhatsApp y redes. Handoff al humano cuando toca cerrar la venta.",
      },
      {
        tag: "03",
        name: "Automatización de ventas",
        desc: "Del lead al seguimiento, la cita o el pedido. Menos chase manual, más consistencia en el embudo.",
      },
      {
        tag: "04",
        name: "Consultoría y análisis",
        desc: "Diagnóstico de embudo: comparamos captación (Meta y otros) vs cierre real. Muchas veces el problema no son los ads — es que los leads no se convierten en ventas.",
      },
      {
        tag: "05",
        name: "Canales e integraciones",
        desc: "Conectamos tu chatbot de WhatsApp/web con el CRM y las tools que ya usas: el lead viaja solo de la conversación a la etapa correcta, sin copiar y pegar.",
      },
      {
        tag: "06",
        name: "Sistemas a medida",
        desc: "Software pensado para tu operación real — por ejemplo logística en CDGT: rutas por tráfico, flota y entregas en un solo tablero.",
      },
    ],
    process_eyebrow: "Cómo construimos",
    process_title: "Soluciones reales.",
    process_title_accent: "A tu medida.",
    process: [
      {
        n: "01",
        name: "Operación real primero",
        desc: "Partimos de cómo trabaja tu equipo hoy: procesos, canales y fricciones. La solución se diseña alrededor de eso — no alrededor de un demo genérico.",
      },
      {
        n: "02",
        name: "Todo conectado",
        desc: "Web, WhatsApp, tienda, CRM y automatizaciones se hablan entre sí. Menos copiar y pegar; la información fluye entre las piezas del sistema.",
      },
      {
        n: "03",
        name: "Hecho para crecer",
        desc: "Arrancamos con lo que más duele ahora y dejamos la base lista para el siguiente nivel: sin rehacer todo cuando el negocio escala.",
      },
      {
        n: "04",
        name: "Con vos después del live",
        desc: "Lanzar no es el final. Medimos uso real, detectamos fricciones y afinamos la solución con tu operación del día a día.",
      },
    ],
    cta_title: "¿Listo para dejar de perder leads?",
    cta_sub: "Agenda un diagnóstico y revisamos juntos tu embudo, canales e IA comercial.",
    cta_button: "Agendar diagnóstico",
    cta_pill: "Próximo paso",
    book_modal_title: "Agenda una llamada",
    book_modal_subtitle: "Elige fecha y comparte tus datos para contactarte.",
    book_modal_close: "Cerrar",
    book_modal_date: "Fecha",
    book_modal_no_date: "Sin fecha seleccionada",
    book_modal_change_date: "Modificar fecha",
    book_modal_time: "Hora",
    book_modal_time_help: "Selecciona un horario entre 8:00 AM y 4:00 PM.",
    book_modal_no_time: "Sin hora seleccionada",
    book_modal_time_taken: "Ocupado",
    book_modal_pick_time_error: "Selecciona una hora disponible.",
    book_modal_day: "Día",
    book_modal_month: "Mes",
    book_modal_name: "Nombre",
    book_modal_company: "Empresa",
    book_modal_phone: "Teléfono",
    book_modal_email: "Correo",
    book_modal_name_placeholder: "Tu nombre",
    book_modal_company_placeholder: "Nombre de tu empresa",
    book_modal_phone_placeholder: "+1 555 000 0000",
    book_modal_email_placeholder: "tu@empresa.com",
    book_modal_submit: "Enviar solicitud",
    book_modal_sending: "Enviando...",
    book_modal_success: "Listo. Te contactamos pronto para confirmar la llamada.",
    book_modal_network_error: "Ocurrió un error de red. Intenta nuevamente.",
    book_modal_server_error: "No se pudo enviar la solicitud.",
    footer_tag: "Sistemas de venta digital: IA, automatización y e-commerce.",
    footer_made: "Hecho en Guatemala",
    footer_terms: "Términos y condiciones",
    footer_privacy: "Política de privacidad",
    footer_deletion: "Eliminación de datos",
    legal_close: "Cerrar",
    legal_back: "Volver al inicio",
    demo_cart_aria: "Carrito de compras",
    ecommerce_checkout: "Checkout",
    custom_apps_eyebrow: "Apps a la medida",
    custom_apps_hero_title: ["Web y móvil", "hechas para", "tu operación."],
    custom_apps_hero_sub:
      "Diseñamos y construimos aplicaciones alrededor de tu flujo real: integraciones, roles, analítica y despliegue. Prototipo rápido, entregas en sprints y equipo in-house de punta a punta.",
    custom_apps_cta_home: "Volver al inicio",
    automation_eyebrow: "Automatizaciones",
    automation_hero_title: ["Tu operación", "en piloto", "automático."],
    automation_hero_sub:
      "Integramos formularios, CRMs, mensajería y planillas. Reglas claras, reintentos, auditoría y alertas cuando algo falla. Lo ensayamos contigo antes de producción.",
    automation_cta_home: "Volver al inicio",
    custom_apps_spline_empty:
      "Añade la URL de Embed de tu escena Spline en el archivo de configuración (ver comentarios en el archivo).",
    footer_status: "Aceptando proyectos",
    about_eyebrow: "Quiénes somos",
    about_hero_title: ["Ventas", "con sistema."],
    about_hero_sub:
      "Oktae construye el sistema digital con el que tu negocio responde, da seguimiento y vende. No vendemos horas sueltas: entregamos un flujo comercial que trabaja contigo.",
    about_mission_title: "Nuestra misión",
    about_mission_body:
      "Acercar ventas automatizadas e IA a empresas en LATAM que no tienen un equipo de producto. Creemos que un negocio bien digitalizado en su embudo puede competir con cualquiera.",
    about_values: [
      { icon: "⚡", title: "Velocidad con criterio", desc: "Entregamos rápido sin saltarnos lo importante. Prototipo en días, producto sólido." },
      { icon: "🔩", title: "Sin intermediarios", desc: "El equipo que diseña es el que construye y opera. Sin agencias de por medio." },
      { icon: "📐", title: "A medida, siempre", desc: "No usamos templates. Cada solución se diseña desde el problema real del cliente." },
      { icon: "🌎", title: "LATAM + USA", desc: "Operamos en dos contextos distintos y sabemos cómo conectarlos." },
    ],
    about_team_eyebrow: "Liderazgo",
    about_team_name: "Gustavo Ortiz",
    about_team_role: "Director de Tecnología & Fundador",
    about_team_linkedin: "https://www.linkedin.com/in/ortizggustavo/",
    about_team_bio: [
      "Ingeniero de software con más de 10 años liderando proyectos de tecnología en LATAM y Estados Unidos. Ha construido sistemas para industrias de alta exigencia: fintech, construcción, hotelería y retail.",
      "Fundó Oktae con la convicción de que las empresas medianas merecen el mismo nivel de tecnología que las grandes corporaciones, entregado con la agilidad de un equipo compacto y comprometido.",
    ],
    about_cta_home: "Volver al inicio",
    clients: ["NIDRA", "Calexa", "Veridian", "Polara", "Mantis Co.", "Atlas Fresh", "Norte", "Helio", "Lumière"],
    projects_eyebrow: "Trabajo",
    projects_title: "Proyectos recientes",
    projects_carousel_label: "Galería de proyectos",
    projects_slide_alt: (n: number) => `Proyecto ${n}`,
    projects_prev: "Proyecto anterior",
    projects_next: "Proyecto siguiente",
    projects_go_to: (n: number) => `Ir al proyecto ${n}`,
    projects_items: [
      {
        src: "/pic1.png",
        title: "Sindicación de capital automatizada",
        industry: "Merchant Cash Advance · USA",
        brief:
          "Plataforma de sindicación de capital con control de inversionistas, deals y capital privado para operaciones MCA en Estados Unidos.",
      },
      {
        src: "/pic2.png",
        title: "Análisis inteligente de riesgo comercial",
        industry: "Small business lending · USA",
        brief:
          "Motor de riesgo que analiza estados financieros, tendencias de mercado, fraude documental, oferta sugerida y detección de stacking, entre otras señales.",
      },
      {
        src: "/pic3.png",
        title: "Control de proyectos de construcción",
        industry: "Construcción · LATAM",
        brief:
          "Sistema para predecir el avance del capital del proyecto, con control de materiales, planilla y equipo de management en un solo lugar.",
      },
      {
        src: "/pic4.png",
        title: "E-commerce de marca premium",
        industry: "Retail · Guatemala",
        brief:
          "Tienda online para una marca exclusiva de beanies guatemalteca, pensada para conversión y operación diaria del catálogo.",
      },
      {
        src: "/pic5.png",
        title: "Reservas hoteleras integradas",
        industry: "Hospitalidad · LATAM",
        brief:
          "Sitio de reservación conectado a un sistema hotelero de gestión, CRM y módulos operativos para el equipo comercial y de recepción.",
      },
    ],
    ecommerce_eyebrow: "E-commerce",
    ecommerce_hero_title: ["Tiendas que", "venden más", "en tu industria."],
    ecommerce_hero_sub:
      "Diseñamos y construimos e-commerce a medida para distintas industrias: catálogo, checkout, pagos locales, inventario y logística integrada a cómo ya operas.",
    ecommerce_bullets: [
      "Checkout optimizado y pagos locales",
      "Catálogo, filtros y variantes por rubro",
      "Integración con ERP, inventario y envíos",
    ],
    ecommerce_industries: [
      "Retail",
      "Telecom",
      "Alimentos",
      "B2B",
      "Mayoristas",
      "Servicios",
    ],
    ecommerce_cta_home: "Volver al inicio",
    ecommerce_frame_url: "tienda.ejemplo.com/catalogo",
    ecommerce_frame_alt: "Ejemplo de catálogo e-commerce en producción",
    ecommerce_frame_caption: "Ejemplo visual · cliente telecom retail",
  },
  en: {
    nav: ["Services", "Principles", "Work", "About"],
    cta_nav: "Let’s talk",
    hero_eyebrow: "AI-powered digital sales · LATAM",
    hero_title: ["Tech That", "Grows", "with Your Business"],
    hero_sub:
      "We design and build the digital platforms your business needs: AI chatbots on web and social, automated systems, and online stores. Technology ready to scale when you are.",
    hero_cta: "Book a diagnostic",
    hero_cta_2: "See our services",
    clients_eyebrow: "Teams and brands we build with",
    clients_title: "Trusted by teams scaling with Oktae",
    sites_scroll_eyebrow: "Live sites",
    sites_scroll_aria: "Websites we build",
    sites_scroll_lead: "We build websites that",
    sites_scroll_switcher: "Switch site",
    sites_scroll_open: "Open",
    sites_scroll_pending: "Preview unavailable.",
    stats: [
      { k: "24/7", v: "coverage on your channels" },
      { k: "1", v: "system from lead to close" },
      { k: "AI", v: "on web, WhatsApp & social" },
      { k: "LATAM", v: "build and support" },
    ],
    services_eyebrow: "How we help you grow",
    services_title: "Our services",
    services_title_accent: "end to end.",
    services_sub:
      "Store, chatbot, automation, CRM, even custom systems — each layer is built so leads don’t go cold. When ads already bring people in, we look at the close — and make it measurable.",
    services: [
      {
        tag: "01",
        name: "E-commerce",
        desc: "Stores and catalogs built to convert: checkout, local payments, inventory, wired to your sales conversation.",
      },
      {
        tag: "02",
        name: "AI chatbots",
        desc: "Response and qualification on web, WhatsApp, and social. Human handoff when it’s time to close.",
      },
      {
        tag: "03",
        name: "Sales automation",
        desc: "From lead to follow-up, booking, or order. Less manual chase, more consistency in the funnel.",
      },
      {
        tag: "04",
        name: "Consulting & analysis",
        desc: "Funnel diagnosis: we compare acquisition (Meta and others) vs real closes. Often ads aren’t the issue — leads just aren’t converting into sales.",
      },
      {
        tag: "05",
        name: "Channels & integrations",
        desc: "We wire your WhatsApp/web chatbot to the CRM and tools you already use — the lead moves from the conversation to the right stage with no copy-paste.",
      },
      {
        tag: "06",
        name: "Custom systems",
        desc: "Software built around how you actually operate — e.g. Guatemala City logistics: traffic-aware routes, fleet and deliveries on one board.",
      },
    ],
    process_eyebrow: "How we build",
    process_title: "Real solutions.",
    process_title_accent: "Built around you.",
    process: [
      {
        n: "01",
        name: "Your operation first",
        desc: "We start from how your team works today: processes, channels, and friction. The solution is shaped around that — not around a generic demo.",
      },
      {
        n: "02",
        name: "Everything connected",
        desc: "Web, WhatsApp, store, CRM, and automations talk to each other. Less copy-paste; information flows across the system.",
      },
      {
        n: "03",
        name: "Built to grow",
        desc: "We start with what hurts most now and leave the base ready for the next level — no full rebuild when the business scales.",
      },
      {
        n: "04",
        name: "With you after go-live",
        desc: "Launch isn’t the end. We measure real use, surface friction, and tune the solution with how you operate day to day.",
      },
    ],
    cta_title: "Ready to stop losing leads?",
    cta_sub: "Book a diagnostic and we’ll review your funnel, channels, and commercial AI together.",
    cta_button: "Book a diagnostic",
    cta_pill: "Next step",
    book_modal_title: "Book a call",
    book_modal_subtitle: "Choose a date and share your details so we can contact you.",
    book_modal_close: "Close",
    book_modal_date: "Date",
    book_modal_no_date: "No date selected",
    book_modal_change_date: "Change date",
    book_modal_time: "Time",
    book_modal_time_help: "Pick a slot between 8:00 AM and 4:00 PM.",
    book_modal_no_time: "No time selected",
    book_modal_time_taken: "Booked",
    book_modal_pick_time_error: "Select an available time slot.",
    book_modal_day: "Day",
    book_modal_month: "Month",
    book_modal_name: "Name",
    book_modal_company: "Company",
    book_modal_phone: "Phone",
    book_modal_email: "Email",
    book_modal_name_placeholder: "Your name",
    book_modal_company_placeholder: "Your company name",
    book_modal_phone_placeholder: "+1 555 000 0000",
    book_modal_email_placeholder: "you@company.com",
    book_modal_submit: "Send request",
    book_modal_sending: "Sending...",
    book_modal_success: "Done. We will contact you soon to confirm the call.",
    book_modal_network_error: "A network error occurred. Please try again.",
    book_modal_server_error: "Could not send the request.",
    footer_tag: "Digital sales systems: AI, automation, and e-commerce.",
    footer_made: "Built in Guatemala, active anywhere",
    footer_terms: "Terms and conditions",
    footer_privacy: "Privacy policy",
    footer_deletion: "Data deletion",
    legal_close: "Close",
    legal_back: "Back to home",
    demo_cart_aria: "Shopping cart",
    ecommerce_checkout: "Checkout",
    custom_apps_eyebrow: "Custom apps",
    custom_apps_hero_title: ["Web & mobile", "built for", "your operations."],
    custom_apps_hero_sub:
      "We design and ship apps around your real workflow: integrations, roles, analytics and deployment. Fast prototypes, sprint deliveries and an in-house team end to end.",
    custom_apps_cta_home: "Back to home",
    automation_eyebrow: "Automations",
    automation_hero_title: ["Your ops,", "on autopilot", "— wired right."],
    automation_hero_sub:
      "We connect forms, CRMs, messaging and spreadsheets. Clear rules, retries, audit trails and alerts when something breaks. We rehearse with you before production.",
    automation_cta_home: "Back to home",
    custom_apps_spline_empty:
      "Add your Spline embed URL in the config file (see comments there).",
    footer_status: "",
    about_eyebrow: "Who we are",
    about_hero_title: ["Sales", "with a system."],
    about_hero_sub:
      "Oktae builds the digital system that helps your business reply, follow up, and sell. We don’t sell loose hours — we deliver a commercial flow that works with you.",
    about_mission_title: "Our mission",
    about_mission_body:
      "To bring automated sales and AI to LATAM businesses that don’t have an in-house product team. A well-digitalized funnel can compete with anyone.",
    about_values: [
      { icon: "⚡", title: "Speed with judgment", desc: "We ship fast without cutting corners. Prototype in days, solid product." },
      { icon: "🔩", title: "No middlemen", desc: "The team that designs is the one that builds and operates. No agency layers." },
      { icon: "📐", title: "Custom, always", desc: "We don't use templates. Every solution is designed from the client's real problem." },
      { icon: "🌎", title: "LATAM + USA", desc: "We operate in two different contexts and know how to connect them." },
    ],
    about_team_eyebrow: "Leadership",
    about_team_name: "Gustavo Ortiz",
    about_team_role: "Chief Technology Officer & Founder",
    about_team_linkedin: "https://www.linkedin.com/in/ortizggustavo/",
    about_team_bio: [
      "Software engineer with over 10 years leading technology projects across LATAM and the United States. He has built systems for demanding industries: fintech, construction, hospitality and retail.",
      "He founded Oktae with the belief that mid-sized companies deserve the same level of technology as large corporations — delivered with the agility of a tight, committed team.",
    ],
    about_cta_home: "Back to home",
    clients: ["NIDRA", "Calexa", "Veridian", "Polara", "Mantis Co.", "Atlas Fresh", "Norte", "Helio", "Lumière"],
    projects_eyebrow: "Work",
    projects_title: "Recent projects",
    projects_carousel_label: "Project gallery",
    projects_slide_alt: (n: number) => `Project ${n}`,
    projects_prev: "Previous project",
    projects_next: "Next project",
    projects_go_to: (n: number) => `Go to project ${n}`,
    projects_items: [
      {
        src: "/pic1.png",
        title: "Automated capital syndication",
        industry: "Merchant Cash Advance · USA",
        brief:
          "Capital syndication platform with investor controls, deal flow and private capital management for MCA operations in the United States.",
      },
      {
        src: "/pic2.png",
        title: "Intelligent commercial risk analysis",
        industry: "Small business lending · USA",
        brief:
          "Risk engine that reads financial statements, market trends, document fraud, suggested offers and stacking detection, among other signals.",
      },
      {
        src: "/pic3.png",
        title: "Construction project control",
        industry: "Construction · LATAM",
        brief:
          "System to forecast project capital progress, with materials, payroll and management team tracking in one workspace.",
      },
      {
        src: "/pic4.png",
        title: "Premium brand e-commerce",
        industry: "Retail · Guatemala",
        brief:
          "Online store for an exclusive Guatemalan beanie brand, built for conversion and day-to-day catalog operations.",
      },
      {
        src: "/pic5.png",
        title: "Integrated hotel bookings",
        industry: "Hospitality · LATAM",
        brief:
          "Booking site wired to a property management system, CRM and operational modules for sales and front-desk teams.",
      },
    ],
    ecommerce_eyebrow: "E-commerce",
    ecommerce_hero_title: ["Stores that", "sell more", "in your industry."],
    ecommerce_hero_sub:
      "We design and build custom e-commerce for different industries: catalog, checkout, local payments, inventory and logistics wired to how you already operate.",
    ecommerce_bullets: [
      "Conversion-focused checkout and local payments",
      "Catalog, filters and variants per vertical",
      "ERP, inventory and shipping integrations",
    ],
    ecommerce_industries: [
      "Retail",
      "Telecom",
      "Food",
      "B2B",
      "Wholesale",
      "Services",
    ],
    ecommerce_cta_home: "Back to home",
    ecommerce_frame_url: "store.example.com/catalog",
    ecommerce_frame_alt: "Example e-commerce catalog in production",
    ecommerce_frame_caption: "Visual example · telecom retail client",
  },
} as const;

export type CopyShape = (typeof COPY)[Lang];
