export type Lang = "es" | "en";

export const COPY = {
  es: {
    nav: ["Servicios", "Proceso", "Trabajo", "Contacto"],
    cta_nav: "Hablemos",
    hero_eyebrow: "Estudio de tecnología · LATAM + USA",
    hero_title: ["Construimos", "el software", "que tu negocio", "necesita ahora."],
    hero_sub:
      "Oktae es una agencia de tecnología para PYMEs. Diseñamos y construímos e-commerce, smart dashboards y aplicaciones a la medida.",
    hero_cta: "Agendar llamada",
    hero_cta_2: "Ver servicios",
    stats: [
      { k: "45+", v: "proyectos lanzados" },
      { k: "12", v: "industrias atendidas" },
      { k: "7 días", v: "a primer prototipo" },
      { k: "99.9%", v: "uptime en producción" },
    ],
    services_eyebrow: "Lo que hacemos",
    services_title: "Un equipo, todo el stack.",
    services_sub:
      "Desde la idea hasta la operación. Sin agencias intermediarias, sin retrasos, sin sorpresas.",
    services: [
      { tag: "01", name: "E-commerce", desc: "Tiendas optimizadas para conversión, integradas a tu logística y pagos locales." },
      { tag: "02", name: "Apps a la medida", desc: "Aplicaciones web y móviles construidas para tu flujo, no para el de un template." },
      { tag: "03", name: "Automatizaciones", desc: "Conectamos tus herramientas y eliminamos el trabajo manual silencioso." },
      { tag: "04", name: "Smart Dashboards", desc: "Decisiones basadas en datos en tiempo real, no en planillas a fin de mes." },
      { tag: "05", name: "Apps Móviles", desc: "iOS y Android nativos o cross-platform, según lo que necesite tu producto." },
      { tag: "06", name: "Soluciones a medida", desc: "Si lo puedes describir, lo podemos construir. Tecnología sin etiquetas." },
    ],
    process_eyebrow: "Cómo trabajamos",
    process_title: "Cuatro pasos. Cero ruido.",
    process: [
      { n: "01", name: "Descubrir", desc: "Entendemos tu negocio, tu cliente y dónde está la fricción real." },
      { n: "02", name: "Diseñar", desc: "Prototipamos rápido. Validamos antes de escribir una línea de código." },
      { n: "03", name: "Construir", desc: "Sprints cortos, demos semanales. Lo ves crecer en vivo." },
      { n: "04", name: "Operar", desc: "Lanzamos, medimos y mejoramos. No te dejamos solo después del go-live." },
    ],
    cta_title: "¿Listo para construir?",
    cta_sub: "",
    cta_button: "Reservar llamada",
    cta_pill: "Próximo paso",
    book_modal_title: "Agenda una llamada",
    book_modal_subtitle: "Elige fecha y comparte tus datos para contactarte.",
    book_modal_close: "Cerrar",
    book_modal_date: "Fecha",
    book_modal_no_date: "Sin fecha seleccionada",
    book_modal_change_date: "Modificar fecha",
    book_modal_time: "Hora",
    book_modal_time_help: "Selecciona un horario entre 8:00 AM y 4:00 PM.",
    book_modal_no_time: "Sin hora seleccionada",
    book_modal_time_taken: "Ocupado",
    book_modal_pick_time_error: "Selecciona una hora disponible.",
    book_modal_day: "Día",
    book_modal_month: "Mes",
    book_modal_name: "Nombre",
    book_modal_company: "Empresa",
    book_modal_phone: "Teléfono",
    book_modal_email: "Correo",
    book_modal_name_placeholder: "Tu nombre",
    book_modal_company_placeholder: "Nombre de tu empresa",
    book_modal_phone_placeholder: "+1 555 000 0000",
    book_modal_email_placeholder: "tu@empresa.com",
    book_modal_submit: "Enviar solicitud",
    book_modal_sending: "Enviando...",
    book_modal_success: "Listo. Te contactamos pronto para confirmar la llamada.",
    book_modal_network_error: "Ocurrió un error de red. Intenta nuevamente.",
    book_modal_server_error: "No se pudo enviar la solicitud.",
    footer_tag: "Estudio digital para LATAM y USA.",
    footer_made: "Hecho en Guatemala",
    demo_cart_aria: "Carrito de compras",
    ecommerce_checkout: "Checkout",
    custom_apps_eyebrow: "Apps a la medida",
    custom_apps_hero_title: ["Web y móvil", "hechas para", "tu operación."],
    custom_apps_hero_sub:
      "Diseñamos y construimos aplicaciones alrededor de tu flujo real: integraciones, roles, analítica y despliegue. Prototipo rápido, entregas en sprints y equipo in-house de punta a punta.",
    custom_apps_cta_home: "Volver al inicio",
    custom_apps_spline_empty:
      "Añade la URL de Embed de tu escena Spline en el archivo de configuración (ver comentarios en el archivo).",
    footer_status: "Aceptando proyectos Q3",
    clients: ["NIDRA", "Calexa", "Veridian", "Polara", "Mantis Co.", "Atlas Fresh", "Norte", "Helio", "Lumière"],
  },
  en: {
    nav: ["Services", "Process", "Work", "Contact"],
    cta_nav: "Let’s talk",
    hero_eyebrow: "Tech studio · LATAM + USA",
    hero_title: ["We build", "the software", "your business", "needs now."],
    hero_sub:
      "Oktae is a digital agency, we ship e-commerce, smart dashboards and custom apps. We understand your business and we're ready to build what your business needs.",
    hero_cta: "Book a call",
    hero_cta_2: "See services",
    stats: [
      { k: "45+", v: "projects launched" },
      { k: "12", v: "industries served" },
      { k: "7 days", v: "to first prototype" },
      { k: "99.9%", v: "production uptime" },
    ],
    services_eyebrow: "What we do",
    services_title: "One team, the whole stack.",
    services_sub: "From idea to operation. No middle agencies, no delays, no surprises.",
    services: [
      { tag: "01", name: "E-commerce", desc: "Stores tuned for conversion, integrated with your logistics and local payments." },
      { tag: "02", name: "Custom apps", desc: "Web and mobile apps built around your workflow, not a template’s." },
      { tag: "03", name: "Automations", desc: "We connect your tools and kill the silent manual work." },
      { tag: "04", name: "Smart dashboards", desc: "Real-time, data-driven decisions — not month-end spreadsheets." },
      { tag: "05", name: "Mobile apps", desc: "Native or cross-platform iOS and Android — whichever your product needs." },
      { tag: "06", name: "Custom solutions", desc: "If you can describe it, we can build it. Tech with no labels." },
    ],
    process_eyebrow: "How we work",
    process_title: "Four steps. Zero noise.",
    process: [
      { n: "01", name: "Discover", desc: "We understand your business, your customer, and where the real friction is." },
      { n: "02", name: "Design", desc: "We prototype fast. We validate before writing a single line of code." },
      { n: "03", name: "Build", desc: "Short sprints, weekly demos. You watch it grow live." },
      { n: "04", name: "Operate", desc: "We launch, measure and improve. We don’t leave you alone after go-live." },
    ],
    cta_title: "Ready to build?",
    cta_sub: "",
    cta_button: "Book a call",
    cta_pill: "Next step",
    book_modal_title: "Book a call",
    book_modal_subtitle: "Choose a date and share your details so we can contact you.",
    book_modal_close: "Close",
    book_modal_date: "Date",
    book_modal_no_date: "No date selected",
    book_modal_change_date: "Change date",
    book_modal_time: "Time",
    book_modal_time_help: "Pick a slot between 8:00 AM and 4:00 PM.",
    book_modal_no_time: "No time selected",
    book_modal_time_taken: "Booked",
    book_modal_pick_time_error: "Select an available time slot.",
    book_modal_day: "Day",
    book_modal_month: "Month",
    book_modal_name: "Name",
    book_modal_company: "Company",
    book_modal_phone: "Phone",
    book_modal_email: "Email",
    book_modal_name_placeholder: "Your name",
    book_modal_company_placeholder: "Your company name",
    book_modal_phone_placeholder: "+1 555 000 0000",
    book_modal_email_placeholder: "you@company.com",
    book_modal_submit: "Send request",
    book_modal_sending: "Sending...",
    book_modal_success: "Done. We will contact you soon to confirm the call.",
    book_modal_network_error: "A network error occurred. Please try again.",
    book_modal_server_error: "Could not send the request.",
    footer_tag: "Digital studio for LATAM and the USA.",
    footer_made: "Built in Guatemala, active anywhere",
    demo_cart_aria: "Shopping cart",
    ecommerce_checkout: "Checkout",
    custom_apps_eyebrow: "Custom apps",
    custom_apps_hero_title: ["Web & mobile", "built for", "your operations."],
    custom_apps_hero_sub:
      "We design and ship apps around your real workflow: integrations, roles, analytics and deployment. Fast prototypes, sprint deliveries and an in-house team end to end.",
    custom_apps_cta_home: "Back to home",
    custom_apps_spline_empty:
      "Add your Spline embed URL in the config file (see comments there).",
    footer_status: "",
    clients: ["NIDRA", "Calexa", "Veridian", "Polara", "Mantis Co.", "Atlas Fresh", "Norte", "Helio", "Lumière"],
  },
} as const;

export type CopyShape = (typeof COPY)[Lang];
